name: Check Product Prices

on:
  schedule:
    # Run every 3 minutes
    - cron: "*/3 * * * *"
  workflow_dispatch: # Allows manual triggering

# Add permissions for the GitHub bot
permissions:
  contents: write
  pull-requests: write

jobs:
  check-prices:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run price checker
        env:
          FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          PRICE_DROP_THRESHOLD: 0.05
        run: python src/scraper.py

      - name: Commit price history
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/price_history.db
          git commit -m "Update price history" || echo "No changes to commit"
          git push
